general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'referenceappscf'
      space: 'espm'
      credentialsId: 'CF_CREDENTIALSID'  
